const ACTIONS = {
    LOGIN_USER: "LOGIN_USER",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    USER_LOGGED_IN: "USER_LOGGED_IN",
    LOGOUT_USER: "LOGOUT_USER"
};

export default ACTIONS;