export const AUTHACTIONS = {
    LOGIN_USER: "LOGIN_USER",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    REGISTER_USER: "REGISTER_USER",
    REGISTER_FAILURE: "REGISTER_FAILURE",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    USER_LOGGED_IN: "USER_LOGGED_IN",
    LOGOUT_USER: "LOGOUT_USER",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
    REMOVE_ERROR: "REMOVE_ERROR"
};

export const CATEGORYACTIONS = {
    FETCH_CATEGORIES: "FETCH_CATEGORIES",
    FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
    FETCH_CATEGORIES_FAILURE: "FETCH_CATEGORIES_FAILURE",
    ADD_CATEGORY: "ADD_CATEGORY",
    ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
    ADD_CATEGORY_FAILURE: "ADD_CATEGORY_FAILURE"
};

export const PRODUCTACTIONS = {
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
    FETCH_PRODUCTS_FAILURE: "FETCH_PRODUCTS_FAILURE",
    ADD_PRODUCT: "ADD_PRODUCT",
    ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
    ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE"
};