const ACTIONS = {
    LOGIN_USER: "LOGIN_USER",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    REGISTER_USER: "REGISTER_USER",
    REGISTER_FAILURE: "REGISTER_FAILURE",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    USER_LOGGED_IN: "USER_LOGGED_IN",
    LOGOUT_USER: "LOGOUT_USER",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
    REMOVE_ERROR: "REMOVE_ERROR"
};

export default ACTIONS;